### ISSUE TITLE
Error while converting nupkg to jar via roslyn generator

### ISSUE THREAD

**Issue by kumardharm** [SonarSource/sonarqube-roslyn-sdk#107] opened 2019-02-07 09:50 UTC
Created own Analyzer from VS 2017 and created the nuget pack but whenever I am trying to convert the nupkg to jar via roslyn generator .

**Error:**
Looking for analyzers in the package...
[DEBUG] Looking for C# analyzers
[DEBUG] Adding AssemblyResolver to current AppDomain assembly resolution.
Loaded assembly: Analyzer1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
[DEBUG] Attempting to resolve assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', requested by '{unknown}'
[DEBUG] Failed to resolve assembly.
Could not instantiate analyzers from 'Analyzer1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[DEBUG] Removed AssemblyResolver from current AppDomain assembly resolution.
[WARNING] No analyzers were found in package: Analyzer1
[WARNING] Re-run this generator with /recurse if plugins should be generated for the dependencies of this package.

**Comment by duncanp-sonar** [comment] 2019-02-27 17:45
Duplicate of #104

**Closed by duncanp-sonar** 2019-02-27 17:45 UTC
